#!/usr/bin/env bash
# Configures Ubuntu server: localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8
sed 's/127\.0\.0\.1\(.*\)localhost/127.0.0.2\1localhost/' /etc/hosts > /tmp/hosts
cat /tmp/hosts > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
